# Managed by Terraform in https://github.com/INITOPS-TEAM/buried-marks-terraform.
# All changes would be discarded after `terraform apply` in buried-marks-terraform repository.

name: Build and Push to ECR

on:
  push:
    branches:
    - main
  release:
    types:
    - published

permissions:
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::995303881249:role/github-service
        aws-region: eu-north-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.1.0

    - name: Build and push
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
      run: |
        docker build -t 995303881249/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag 995303881249/$ECR_REPOSITORY:$IMAGE_TAG 995303881249/$ECR_REPOSITORY:latest
        docker push 995303881249/$ECR_REPOSITORY:$IMAGE_TAG
        docker push 995303881249/$ECR_REPOSITORY:latest
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::492052863680:role/github-service
        aws-region: eu-north-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.1.0

    - name: Build and push
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
      run: |
        docker build -t 492052863680/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag 492052863680/$ECR_REPOSITORY:$IMAGE_TAG 492052863680/$ECR_REPOSITORY:latest
        docker push 492052863680/$ECR_REPOSITORY:$IMAGE_TAG
        docker push 492052863680/$ECR_REPOSITORY:latest
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::833822972731:role/github-service
        aws-region: eu-north-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.1.0

    - name: Build and push
      env:
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
      run: |
        docker build -t 833822972731/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag 833822972731/$ECR_REPOSITORY:$IMAGE_TAG 833822972731/$ECR_REPOSITORY:latest
        docker push 833822972731/$ECR_REPOSITORY:$IMAGE_TAG
        docker push 833822972731/$ECR_REPOSITORY:latest
    
