# Managed by Terraform in https://github.com/INITOPS-TEAM/buried-marks-terraform.
# All changes would be discarded after `terraform apply` in buried-marks-terraform repository.

name: Build and Push to ECR

on:
  push:
    branches:
    - main
  release:
    types:
    - published

permissions:
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::995303881249:role/github-service
        aws-region: eu-north-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2.1.0

    - name: Build and push
      env:
        ECR_REGISTRY: "995303881249.dkr.ecr.eu-north-1.amazonaws.com"
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./services/${{matrix.service}}
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::492052863680:role/github-service
        aws-region: eu-north-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2.1.0

    - name: Build and push
      env:
        ECR_REGISTRY: "492052863680.dkr.ecr.eu-north-1.amazonaws.com"
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./services/${{matrix.service}}
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::833822972731:role/github-service
        aws-region: eu-north-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2.1.0

    - name: Build and push
      env:
        ECR_REGISTRY: "833822972731.dkr.ecr.eu-north-1.amazonaws.com"
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.event_name == 'release' && github.ref_name || github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./services/${{matrix.service}}
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
